### ISSUE TITLE
change SqlVar::type to enum

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#124]
Along with `enum SqlVarType SqlVar::getType()` and `std::vector<enum SqlVarType> param_types;` - cast to/from int where absolute necessary - but keep as enum wherever possible.

This would ease debugging and for some places may provide type safety, too.

**Comment by mridoni** [comment]
This, among other things, is an holdover from the C/ocesql roots of GixSQL, there are also a few places where pointer lists  are passed as `int *` plus an additional `int` for length, instead of something like `const std::vector<int>&` (or string). This needs to change, for all the reasons you enumerated.

**Comment by mridoni** [comment]
This is already in https://github.com/mridoni/gixsql/tree/v1.0.20dev. I am not closing the issue until the branch is merged into main.
